apiVersion: v1
kind: Service
metadata:
  name: movie-recommendation-service
spec:
  selector:
    app: movie-recommendation
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer